web:
  build: .
  links:
    - db
  volumes:
    - .:/var/www/invoice
  ports:
    - "80:80"
db:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: invoice
    MYSQL_DATABASE: invoice
  ports:
    - "3306:3306"
  volumes:
    - /mnt/sda1/var/lib/invoice-data:/var/lib/mysql
    - ${PWD}/docker/db/my.cnf:/etc/mysql/my.cnf
